version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - "type/chore"
      - "area/build"
      - "skip-issue-link"
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "type/chore"
      - "area/build"
      - "skip-issue-link"
    commit-message:
      prefix: "chore(ci)"
